# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf1c4e63b011d4728f9a97cd4f5f0dae1932446bfefd821e4ae8caaead31047f5a231731dbdc46d9d6a0c21ef542818b6ca427225f68948743e5650c1129fa0e

test:
  secret_key_base: 0763258f6b743343b495b719438bc799f82008031592bc8e5a8638c7c3072a7668f6d99de115c892635e3498768e37feb067cd3c7629704ca496016d2e74069e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
